# Apparently this is the "official" way to silence NOTEs generated by R CMD check about symbols
# in pipelines which it misperceives as globals (https://github.com/tidyverse/magrittr/issues/29).
if(getRversion() >= "2.15.1")  utils::globalVariables(c('correct','correct_response','correct_responses','key_press','lag',
  'phase','rt','stim','t1_correct','t2_correct','test_part','trial_number'))

#' Process RSVP Task data file
#'
#' \code{process_rsvp()} processes data files generated by the RSVP task
#' (\url{https://earcanal.github.io/rsvp-task/}).
#'
#'@examples
#'\dontrun{
#'rsvp_df <- expand.grid(token = participants$token) %>%
#'  mutate(path=paste('data/', token, '_finished/rsvp-task-results.json', sep=''))
#'rsvp_df <- rsvp_df %>%
#'group_by(token) %>%
#'  do(., process_rsvp(.$path, .$token)) %>%
#'  ungroup %>%
#'  left_join(participants, by='token') %>%
#'  filter(phase == 'test', test_part == "response") %>%
#'  select(p, condition, trial_number, lag, correct, t1_correct, t2_correct, rt)
#'}
#' @param path Path to data file
#' @param p Participant identifier
#' @keywords expfactory rsvp attention blink
#' @importFrom expfactory process_expfactory_experiment
#' @importFrom magrittr %>%
#' @importFrom dplyr filter select mutate
#' @export
#' @return Data frame
process_rsvp <- function(path, p) {
  expfactory::process_expfactory_experiment(path) %>%
    filter(test_part %in% c('rsvp', 'response')) %>%
    mutate(token = p) %>%
    select(token, rt, trial_number, stim, key_press, lag, correct_responses, correct, correct_response,
           t1_correct, t2_correct, phase, test_part)
}