# Apparently this is the "official" way to silence NOTEs generated by R CMD check about symbols
# in pipelines which it misperceives as globals (https://github.com/tidyverse/magrittr/issues/29).
if(getRversion() >= "2.15.1")  utils::globalVariables(c('correct','correct_response','correct_responses','key_press','lag',
  'phase','rt','stim','t1_correct','t2_correct','test_part','trial_number','token'))

#' Process RSVP Task data file
#'
#' \code{process_rsvp()} processes data files generated by the RSVP task
#' (\url{https://earcanal.github.io/rsvp-task/}).
#'
#'@examples
#'\dontrun{
#'rsvp_df <- expand.grid(token = participants$token) %>%
#'  mutate(path=paste('data/', token, '_finished/rsvp-task-results.json', sep=''))
#'rsvp_df <- rsvp_df %>%
#'group_by(token) %>%
#'  do(., process_rsvp(.$path, .$token)) %>%
#'  ungroup %>%
#'  left_join(participants, by='token') %>%
#'  filter(phase == 'test', test_part == "response") %>%
#'  select(p, condition, trial_number, lag, correct, t1_correct, t2_correct, rt)
#'}
#' @param path Path to data file
#' @param p Participant identifier
#' @keywords expfactory rsvp attention blink
#' @importFrom expfactory process_expfactory_experiment
#' @importFrom magrittr %>%
#' @importFrom dplyr filter select mutate
#' @importFrom tidyr replace_na
#' @export
#' @return Data frame
process_rsvp <- function(path, p) {
  df <- expfactory::process_expfactory_experiment(path) %>%
      filter(test_part %in% c('response') & phase != 'instructions') %>%
      mutate(token = p) %>%
      replace_na(list(key_press = FALSE)) %>% # in case P didn't press a key, sets value to 0 (numeric column) i.e. 'invalid response'
      select(token, rt, trial_number, stim, key_press, lag, correct_responses, correct, correct_response,
             t1_correct, t2_correct, phase, test_part)

  # combine pairs of rows into single rows for each trial with analysis-friendly columns 
  rsvp <- data.frame()
  for(i in 0:(nrow(df)/2-1)) {
    r1 <- i*2+1 # response 1
    r2 <- i*2+2 # response 2
    row <- df[r1,c('token','trial_number','phase')]
    row[1,'t1_rt'] <- df[r1,c('rt')]
    row[1,'t2_rt'] <- df[r2,c('rt')]
    row[1,'lag'] <- df[r2,'lag']
    correct <- c(df[r1,'correct_response'], df[r2,'correct_response'])
    responses <- c(df[r1,'key_press'], df[r2,'key_press'])
    
    row[1,'t1_correct'] <- ifelse(df[r1,'correct_response'] %in% responses, TRUE, FALSE)
    # t2|t1
    if(row[1,'t1_correct']) {
      if(df[r2,'key_press'] %in% correct & df[r2,'key_press'] != df[r1,'key_press']) {
        row[1,'t2|t1'] <- TRUE   # T2 is correct if it's one of the correct numbers, and it isn't the same as the T1 response
      } else {
        row[1,'t2|t1'] <- FALSE
      } 
    } else {
      row[1,'t2|t1'] <- FALSE
    }
    rsvp <- rbind(rsvp, row)
  }
  return(rsvp)
}